#!/usr/bin/env bash
# Open the project's console.
#
# Copyright (c) 2019-2021 Cisco Systems.
# License: MIT


set -e
cd "$(dirname "$0")/.."


# Launch the project's console
ipython3 -i script/ipython_console.py
